dbt_databrick_demo:
  target: dev
  outputs:
    dev:
      catalog: '{{ env_var(''DBT_CATALOG'') }}'
      host: '{{ env_var(''DATABRICKS_HOST'') }}'
      http_path: '{{ env_var(''DBT_HTTP_PATH'') }}'
      schema: bronze
      threads: 4
      token: '{{ env_var(''DBT_ENV_SECRET_DB_TOKEN'') }}'
      type: databricks